# Generated by Django 4.1 on 2022-08-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Redeem',
        ),
    ]
