# Generated by Django 4.1 on 2022-08-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voicechat',
            new_name='Discord_VoiceChannel',
        ),
    ]
