# Generated by Django 4.1 on 2022-09-06 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guild', '0002_guild_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='get_guild_as_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guild',
            name='ownership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_guild_as_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guild',
            name='staffs',
            field=models.ManyToManyField(blank=True, related_name='get_guild_as_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guild',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='get_guild_as_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
