# Generated by Django 4.1 on 2022-09-25 04:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_profile_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Discord_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('nickname', models.CharField(max_length=64)),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('avatar_img', models.ImageField(blank=True, null=True, upload_to='discord_member')),
                ('raw_level', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('daily', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('daily_day', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
