# Generated by Django 4.1 on 2022-10-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_discord_account_discordcoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_account',
            name='access',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='discord_account',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discord_account',
            name='refresh',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='discord_account',
            name='token_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
