# Generated by Django 4.1 on 2022-10-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_email_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmation_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
