# Generated by Django 4.1 on 2022-09-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guildname', models.CharField(max_length=12)),
                ('guildname_short', models.CharField(max_length=4)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='guild/banner')),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='guild')),
            ],
        ),
    ]
