# Generated by Django 4.1 on 2022-10-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0003_guild_admins_guild_ownership_guild_staffs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
